CREATE DATABASE IF NOT EXISTS momssi;

CREATE TABLE IF NOT EXISTS member (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `nickname` VARCHAR(255) NOT NULL,
    `admin_yn` CHAR(1) NOT NULL DEFAULT 'N',
    `delete_yn` CHAR(1) NOT NULL DEFAULT 'N',
    `status` VARCHAR(20) NOT NULL DEFAULT 'INACTIVE',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
